# Generated by Django 4.0 on 2021-12-29 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Correo', models.CharField(max_length=200)),
                ('Edad', models.EmailField(max_length=254)),
                ('Sexo', models.CharField(max_length=20)),
                ('Social', models.CharField(max_length=200)),
                ('Facebook', models.IntegerField()),
                ('WhatsApp', models.IntegerField()),
                ('Twitter', models.IntegerField()),
                ('Instagram', models.IntegerField()),
                ('Tiktok', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
