# Generated by Django 4.0.7 on 2022-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Edad',
            field=models.CharField(choices=[('', 'Seleccione su rango de edad'), ('0', '18 a 25'), ('1', '26 a 33'), ('2', '34 a 40'), ('3', '40+')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Sexo',
            field=models.CharField(choices=[('', 'Seleccione horientación sexual'), ('0', 'Hombre'), ('1', 'Mujer'), ('2', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Social',
            field=models.CharField(choices=[('', 'Seleccione red social favorita'), ('0', 'Facebbok'), ('1', 'WhatsApp'), ('2', 'Twitter'), ('3', 'Instagram'), ('4', 'Tiktok'), ('5', 'Otro')], max_length=1),
        ),
    ]
